---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "disk.prefix" . }}-ui-config-map
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.REACT_APP_DISK_API="http{{ if .Values.ingress.tls }}s{{ end }}://{{ with (first .Values.ingress.hosts ) }}{{ .host }}{{ end }}/disk-server/";
